name: Build & Deploy static site

on:
  push:
    branches: [main]      # rebuild every push to main
  workflow_dispatch:      # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Run build script
        run: bun run build/build.ts      # creates dist/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist                    # what to deploy

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4